### ISSUE TITLE
initDevice initialize write buffer with read buffer size

### ISSUE THREAD

**Issue by jbertelson** [jcoenraadts/hid-sharp#1]
The device I'm working with has different buffer sizes for read and write, so I ran into an issue when connecting to it because in HIDInterface.cs, both FS_read and FS_write were initialized with the buffer size capabilities.OutputReportByteLength.  fs_write should use capabilities.InputReportByteLength

**Comment by jcoenraadts** [comment]
Good find. Pushed an update to close this issue.
