### ISSUE TITLE
Some mistakes in the code

### ISSUE THREAD

**Issue by jekyll2014** [jcoenraadts/hid-sharp#3]
1) dll import is incorrect:
there must be "extern" in: private static IntPtr SetupDiGetClassDevs...
2) Need to check if "SN" is integer before "Convert.ToInt32(SN);" in initDevice()
3) Device close causes exception because of async operation still coming (i believe so) in GetInputReportData().
Better insert "if (!this.deviceConnected) return;" in the beginning.
4) Data length size check incorrect in write()
Better make it "if (data.Length > capabilities.OutputReportByteLength - 1)"
Here is the corrected file attached.
Thanks a lot for the library!

[HIDInterface.zip](https://github.com/jcoenraadts/hid-sharp/files/2428089/HIDInterface.zip)

**Comment by jcoenraadts** [comment]
Thanks for you interest in the project. If you have some changes you would like to see, then create them in a new branch and open a pull request to merge them. This Github after all!
